#spring:
#  task:
#    scheduling:
#      pool:
#        size: 12


app:
  queue:
    default-queue-size: 5

  traffic-light:
    default-green-color-duration: 20
    default-yellow-color-duration: 5
    default-red-color-duration: 25

#  log4j:
#  appender:
#    consoleAppender: org.apache.log4j.ConsoleAppender
#      layout: org.apache.log4j.PatternLayout
#        ConversionPattern: [%t] %-5p %c %x - %m%n

