spring:
    main:
      log-startup-info: false
      banner-mode: off


app:
  queue:
    default-queue-size: 5

  traffic-light:
    default-green-color-duration: 20
    default-yellow-color-duration: 5
    default-red-color-duration: 25


logging:
  level:
      com:
        schernoivanov:
          intersectionSimulator: debug